import {DollarSign,Package,ShoppingCart,Users} from "lucide-react";
import PageHeader from "../components/common/PageHeader";
import MetricCard from "../components/dashboard/MetricCard";
import SalesChart from "../components/dashboard/SalesChart";
import CategoryChart from "../components/dashboard/CategoryChart";
import Card from "../components/ui/Card";
import {orders} from "../data/mock";
import StatusBadge from "../components/common/StatusBadge";

export default function DashboardPage(){return <><PageHeader title="Dashboard" subtitle="A complete snapshot of store performance and operations."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={DollarSign} label="Total sales" value="$12,450" change="+10.4%"/><MetricCard icon={ShoppingCart} label="Total orders" value="320" change="+8.1%"/><MetricCard icon={Users} label="Customers" value="1,245" change="+12.6%"/><MetricCard icon={Package} label="Products" value="452" change="+2.1%"/></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><Card className="p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black">Sales overview</h2><p className="text-xs text-gray-400">Last 7 days</p></div><button className="rounded-lg border border-gray-200 px-3 py-2 text-xs font-semibold">Last 7 days</button></div><SalesChart/></Card><Card className="p-5"><h2 className="font-black">Top categories</h2><p className="text-xs text-gray-400">Sales share</p><CategoryChart/></Card></div><Card className="mt-6 overflow-hidden"><div className="flex items-center justify-between border-b border-gray-100 p-5"><h2 className="font-black">Recent orders</h2><a className="text-sm font-bold text-primary-500" href="/orders">View all</a></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-400"><tr><th className="px-5 py-3">Order</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Date</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{orders.slice(0,4).map(order=><tr key={order.id} className="border-t border-gray-100"><td className="px-5 py-4 font-bold text-primary-500">{order.id}</td><td className="px-5 py-4">{order.customer}</td><td className="px-5 py-4 text-gray-500">{order.date}</td><td className="px-5 py-4 font-semibold">${order.amount.toLocaleString()}</td><td className="px-5 py-4"><StatusBadge status={order.status}/></td></tr>)}</tbody></table></div></Card></>}
